//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandbox_Products.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MsSqlConn : DbContext
    {
        public MsSqlConn()
            : base("name=MsSqlConn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductsOperations> ProductsOperations { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<vw_ProductsOperations> vw_ProductsOperations { get; set; }
        public virtual DbSet<vw_ProductsOperationsDetail> vw_ProductsOperationsDetail { get; set; }
        public virtual DbSet<ProductsOperationsTypes> ProductsOperationsTypes { get; set; }
    
        public virtual int GetProductCountById(Nullable<int> productId, ObjectParameter count)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("productId", productId) :
                new ObjectParameter("productId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetProductCountById", productIdParameter, count);
        }
    }
}
